export const ROUTES = {
    home: '/feed',
    login: '/login',
    register: '/register',
    book: '/books/:bookId',
    publishers: '/publishers',
    publisher: '/publishers/:publisherId/details',
    profile: '/profile',
    profileLikedBooks: '/profile/liked',
    publicUserProfile: '/users/:userId/profile',
    categories: '/categories',
    category: '/categories/:categoryId/details',
    authors: '/authors',
    author: '/authors/:authorId',
    submitBook: '/book/submit',
    updateBook: '/book/update/:bookId',
    commentsManagement: '/management/comments',
    categoryManagement: '/management/category',
    bookManagement: '/management/book',
    userManagement: '/management/users',
    authorManagement: '/management/authors',
    error: '/error',
};
